;;; .dir-locals.el --- Leeter project integration
;;; AUTO-GENERATED by `leeter setup emacs`. Re-run to update.
;;; Emacs will ask you to approve this file on first load.
;;; Select "!" to permanently allow it for this project.

((nil . ((eval . (progn
  (load-file "/Users/aryan/leeter/adapters/emacs/leeter.el")
  (leeter-mode 1)
  (message "[leeter] Emacs integration loaded from .dir-locals.el"))))))
