-- Leeter Neovim Integration (auto-generated by `leeter setup neovim`)
-- Requires: vim.o.exrc = true  in your init.lua
-- Re-run `leeter setup neovim` to update after adding new leeter commands.

local leeter = "python3 /Users/aryan/leeter/cli/leeter.py"

local function run_in_term(cmd, cwd)
  vim.cmd("botright 15split")
  local buf = vim.api.nvim_get_current_buf()
  vim.fn.termopen(cmd, { cwd = cwd })
  vim.api.nvim_buf_set_option(buf, "buflisted", false)
end

local function problem_dir()
  return vim.fn.expand("%:p:h")
end

local function repo_root()
  return vim.fn.systemlist("git rev-parse --show-toplevel")[1]
end

-- Keymaps (leader + l prefix = "leeter")
vim.keymap.set("n", "<leader>lr", function() run_in_term(leeter .. " run",              problem_dir()) end, { desc = "Leeter: Run"    })
vim.keymap.set("n", "<leader>ld", function() run_in_term(leeter .. " debug",            problem_dir()) end, { desc = "Leeter: Debug"  })
vim.keymap.set("n", "<leader>lb", function() run_in_term(leeter .. " bench --iters 500",problem_dir()) end, { desc = "Leeter: Bench"  })
vim.keymap.set("n", "<leader>lt", function() run_in_term(leeter .. " stress --iters 200",problem_dir()) end,{ desc = "Leeter: Stress" })
vim.keymap.set("n", "<leader>lp", function() run_in_term(leeter .. " replay",           problem_dir()) end, { desc = "Leeter: Replay" })
vim.keymap.set("n", "<leader>lf", function() run_in_term(leeter .. " fetch",            repo_root())   end, { desc = "Leeter: Fetch"  })
vim.keymap.set("n", "<leader>ls", function() run_in_term(leeter .. " session",          repo_root())   end, { desc = "Leeter: Session"})
vim.keymap.set("n", "<leader>la", function() run_in_term(leeter .. " stats",            repo_root())   end, { desc = "Leeter: Stats"  })

vim.notify("[leeter] Neovim integration loaded. <leader>l + r/d/b/t/p/f/s/a", vim.log.levels.INFO)
