-- Leeter Neovim integration.
-- AUTO-GENERATED by `leeter setup neovim`. Re-run to update.
--
-- Usage: add to your init.lua:
--   require("leeter").setup()          -- default <leader>l prefix
--   require("leeter").setup({ prefix = "<leader>k" })  -- custom prefix

local M = {}

local function run(cmd, cwd)
  local buf = vim.api.nvim_create_buf(false, true)
  local width  = math.floor(vim.o.columns * 0.8)
  local height = math.floor(vim.o.lines   * 0.7)
  vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width    = width,
    height   = height,
    col      = math.floor((vim.o.columns - width)  / 2),
    row      = math.floor((vim.o.lines   - height) / 2),
    style    = "minimal",
    border   = "rounded",
    title    = " " .. cmd .. " ",
  })
  vim.fn.termopen(cmd, { cwd = cwd })
  vim.keymap.set("n", "q", "<cmd>close<cr>", { buffer = buf })
end

local function problem_dir()
  return vim.fn.expand("%:p:h")
end

local function repo_root()
  return vim.fn.systemlist("git rev-parse --show-toplevel")[1]
end

-- Run with --json output and push failures into vim.diagnostic
local function run_with_diagnostics(bin)
  local result = vim.fn.system(bin .. " run --json --problem " .. problem_dir())
  local ok, data = pcall(vim.json.decode, result)
  if not ok or not data or data.status == "error" then
    run(bin .. " run", problem_dir())
    return
  end

  local diagnostics = {}
  for _, case in ipairs((data.payload or {}).cases or {}) do
    if case.status == "fail" then
      table.insert(diagnostics, {
        lnum     = 0,
        col      = 0,
        severity = vim.diagnostic.severity.ERROR,
        message  = string.format(
          "Case %d failed\n  expected: %s\n  got:      %s",
          case.index, case.expected, case.got
        ),
        source = "leeter",
      })
    end
  end

  local bufnr = vim.api.nvim_get_current_buf()
  local ns    = vim.api.nvim_create_namespace("leeter")
  vim.diagnostic.set(ns, bufnr, diagnostics)

  if #diagnostics == 0 then
    local stats = (data.payload or {}).stats or {}
    vim.notify(
      string.format("✓ %d/%d passed", stats.passed or 0, stats.total or 0),
      vim.log.levels.INFO
    )
  end
end

function M.setup(opts)
  opts = opts or {}
  local prefix = opts.prefix or "<leader>l"
  -- resolve binary: honour alias if available, else use absolute path
  local bin = opts.bin or (vim.fn.executable("leeter") == 1 and "leeter" or "python3 " .. debug.getinfo(1, "S").source:sub(2):gsub("adapters/neovim/leeter.lua", "cli/leeter.py"))

  vim.keymap.set("n", prefix .. "r", function() run_with_diagnostics(bin)                    end, { desc = "Leeter: Run"    })
  vim.keymap.set("n", prefix .. "d", function() run(bin .. " debug",            problem_dir()) end, { desc = "Leeter: Debug"  })
  vim.keymap.set("n", prefix .. "b", function() run(bin .. " bench",            problem_dir()) end, { desc = "Leeter: Bench"  })
  vim.keymap.set("n", prefix .. "t", function() run(bin .. " stress",           problem_dir()) end, { desc = "Leeter: Stress" })
  vim.keymap.set("n", prefix .. "p", function() run(bin .. " replay",           problem_dir()) end, { desc = "Leeter: Replay" })
  vim.keymap.set("n", prefix .. "v", function() run(bin .. " paste",            problem_dir()) end, { desc = "Leeter: Paste"  })
  vim.keymap.set("n", prefix .. "f", function()
    local id = vim.fn.input("Problem ID: ")
    if id ~= "" then run(bin .. " fetch " .. id, repo_root()) end
  end, { desc = "Leeter: Fetch" })
  vim.keymap.set("n", prefix .. "s", function() run(bin .. " session", repo_root()) end, { desc = "Leeter: Session" })
  vim.keymap.set("n", prefix .. "a", function() run(bin .. " stats",   repo_root()) end, { desc = "Leeter: Stats"   })

  -- which-key label (no-op if not installed)
  local ok, wk = pcall(require, "which-key")
  if ok then
    wk.register({ l = { name = "Leeter" } }, { prefix = "<leader>" })
  end

  vim.notify("[leeter] Neovim integration loaded. " .. prefix .. " + r/d/b/t/p/v/f/s/a", vim.log.levels.INFO)
end

return M
