import os
from cli.output import renderer

EMACS_TEMPLATE = """;;; .dir-locals.el — Leeter Emacs Integration
;;; Auto-generated by `leeter setup emacs`. Re-run to update.

((nil . ((eval . (progn
  (defvar leeter-bin "{bin}")

  (defun leeter--run (cmd &optional use-repo-root)
    (let* ((default-directory
              (if use-repo-root
                  (locate-dominating-file default-directory ".git")
                default-directory))
           (buf (get-buffer-create "*leeter*")))
      (with-current-buffer buf (erase-buffer))
      (start-process "leeter" buf shell-file-name
                     shell-command-switch
                     (concat leeter-bin " " cmd))
      (display-buffer buf)))

  (defvar leeter-mode-map
    (let ((map (make-sparse-keymap)))
      (define-key map (kbd "C-c l r") (lambda () (interactive) (leeter--run "run")))
      (define-key map (kbd "C-c l d") (lambda () (interactive) (leeter--run "debug")))
      (define-key map (kbd "C-c l b") (lambda () (interactive) (leeter--run "bench --iters 500")))
      (define-key map (kbd "C-c l t") (lambda () (interactive) (leeter--run "stress --iters 200")))
      (define-key map (kbd "C-c l p") (lambda () (interactive) (leeter--run "replay")))
      (define-key map (kbd "C-c l f") (lambda () (interactive) (leeter--run "fetch" t)))
      (define-key map (kbd "C-c l s") (lambda () (interactive) (leeter--run "session" t)))
      (define-key map (kbd "C-c l a") (lambda () (interactive) (leeter--run "stats" t)))
      map))

  (define-minor-mode leeter-mode
    "Minor mode for Leeter keybindings."
    :keymap leeter-mode-map)

  (leeter-mode 1)
  (message "[leeter] Emacs integration loaded. C-c l + r/d/b/t/p/f/s/a"))))))
"""

def setup_emacs(args, bin_cmd: str, merge_tasks, merge_keymap):
    target_file = os.path.abspath(".dir-locals.el")
    content = EMACS_TEMPLATE.format(bin=bin_cmd)
    
    if getattr(args, 'dry_run', False):
        renderer.print(f"Would write to {target_file}:")
        renderer.print(content)
        return
        
    with open(target_file, 'w') as f:
        f.write(content)
    renderer.success(f"Emacs integration written to {target_file}")
    renderer.print("[leeter] .dir-locals.el written. Emacs will ask you to approve it on first open.")
    renderer.print("         Select \"!\" to permanently allow it for this project.")
