import os
import subprocess
from cli.output import renderer

NVIM_TEMPLATE = """-- Leeter Neovim Integration (auto-generated by `leeter setup neovim`)
-- Requires: vim.o.exrc = true  in your init.lua
-- Re-run `leeter setup neovim` to update after adding new leeter commands.

local leeter = "{bin}"

local function run_in_term(cmd, cwd)
  vim.cmd("botright 15split")
  local buf = vim.api.nvim_get_current_buf()
  vim.fn.termopen(cmd, {{ cwd = cwd }})
  vim.api.nvim_buf_set_option(buf, "buflisted", false)
end

local function problem_dir()
  return vim.fn.expand("%:p:h")
end

local function repo_root()
  return vim.fn.systemlist("git rev-parse --show-toplevel")[1]
end

-- Keymaps (leader + l prefix = "leeter")
vim.keymap.set("n", "<leader>lr", function() run_in_term(leeter .. " run",              problem_dir()) end, {{ desc = "Leeter: Run"    }})
vim.keymap.set("n", "<leader>ld", function() run_in_term(leeter .. " debug",            problem_dir()) end, {{ desc = "Leeter: Debug"  }})
vim.keymap.set("n", "<leader>lb", function() run_in_term(leeter .. " bench --iters 500",problem_dir()) end, {{ desc = "Leeter: Bench"  }})
vim.keymap.set("n", "<leader>lt", function() run_in_term(leeter .. " stress --iters 200",problem_dir()) end,{{ desc = "Leeter: Stress" }})
vim.keymap.set("n", "<leader>lp", function() run_in_term(leeter .. " replay",           problem_dir()) end, {{ desc = "Leeter: Replay" }})
vim.keymap.set("n", "<leader>lf", function() run_in_term(leeter .. " fetch",            repo_root())   end, {{ desc = "Leeter: Fetch"  }})
vim.keymap.set("n", "<leader>ls", function() run_in_term(leeter .. " session",          repo_root())   end, {{ desc = "Leeter: Session"}})
vim.keymap.set("n", "<leader>la", function() run_in_term(leeter .. " stats",            repo_root())   end, {{ desc = "Leeter: Stats"  }})

vim.notify("[leeter] Neovim integration loaded. <leader>l + r/d/b/t/p/f/s/a", vim.log.levels.INFO)
"""

WK_TEMPLATE = """
local ok, wk = pcall(require, "which-key")
if ok then
  wk.register({{ l = {{ name = "Leeter" }} }}, {{ prefix = "<leader>" }})
end
"""

def setup_neovim(args, bin_cmd: str, merge_tasks, merge_keymap):
    target_file = os.path.abspath(".nvim.lua")
    content = NVIM_TEMPLATE.format(bin=bin_cmd)
    
    config_dir = os.path.expanduser("~/.config/nvim")
    has_wk = os.path.exists(config_dir) and getattr(args, 'keybindings', False)
    # Very naive heuristic for which-key existence, just append if keybindings is true.
    if has_wk:
        content += WK_TEMPLATE
        
    if getattr(args, 'dry_run', False):
        renderer.print(f"Would write to {target_file}:")
        renderer.print(content)
        return
        
    with open(target_file, 'w') as f:
        f.write(content)
    renderer.success(f"Neovim integration written to {target_file}")
    
    # Check exrc
    try:
        result = subprocess.run(
            ["nvim", "--headless", "-c", "lua print(vim.o.exrc)", "-c", "qa"],
            capture_output=True, text=True
        )
        if "false" in result.stdout:
            renderer.print("[Warning] vim.o.exrc is not enabled. Add `vim.o.exrc = true` to your init.lua")
            renderer.print("          so Neovim auto-loads .nvim.lua when you open this project.")
    except Exception:
        pass # nvim not installed or available in PATH for the check
