/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-variant": "#353434",
        "secondary-fixed-dim": "#c6c5cf",
        "tertiary": "#ffffff",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#46464e",
        "on-primary-fixed": "#1a1c1c",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#454747",
        "on-error": "#690005",
        "on-background": "#e5e2e1",
        "surface-container": "#201f1f",
        "inverse-on-surface": "#313030",
        "on-tertiary": "#2f3131",
        "error": "#ffb4ab",
        "on-primary": "#2f3131",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "secondary-container": "#4a4b53",
        "secondary": "#c6c5cf",
        "on-secondary": "#2f3038",
        "on-primary-container": "#636565",
        "error-container": "#93000a",
        "on-surface": "#e5e2e1",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "surface-dim": "#141313",
        "outline": "#8e9192",
        "on-tertiary-fixed-variant": "#454747",
        "primary": "#ffffff",
        "background": "#141313",
        "primary-fixed": "#e2e2e2",
        "tertiary-container": "#e2e2e2",
        "surface-tint": "#c6c6c7",
        "surface-container-highest": "#353434",
        "surface": "#141313",
        "primary-fixed-dim": "#c6c6c7",
        "surface-container-low": "#1c1b1b",
        "outline-variant": "#444748",
        "inverse-primary": "#5d5f5f",
        "on-tertiary-container": "#636565",
        "on-secondary-container": "#bcbbc5",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-surface-variant": "#c4c7c8",
        "on-secondary-fixed": "#1a1b22",
        "primary-container": "#e2e2e2",
        "tertiary-fixed": "#e2e2e2",
        "secondary-fixed": "#e3e1ec"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sidebar-width": "56px",
        "gutter": "12px",
        "margin-md": "16px",
        "unit": "4px",
        "panel-header-height": "36px",
        "margin-sm": "8px"
      },
      "fontFamily": {
        "code-sm": ["JetBrains Mono"],
        "body-sm": ["Geist"],
        "display": ["Geist"],
        "body-md": ["Geist"],
        "label-caps": ["JetBrains Mono"],
        "code-md": ["JetBrains Mono"],
        "headline": ["Geist"]
      },
      "fontSize": {
        "code-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }],
        "display": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "code-md": ["13px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
