;;; .dir-locals.el — Leeter Emacs Integration
;;; Auto-generated by `leeter setup emacs`. Re-run to update.

((nil . ((eval . (progn
  (defvar leeter-bin "python3 /Users/aryan/leeter/cli/leeter.py")

  (defun leeter--run (cmd &optional use-repo-root)
    (let* ((default-directory
              (if use-repo-root
                  (locate-dominating-file default-directory ".git")
                default-directory))
           (buf (get-buffer-create "*leeter*")))
      (with-current-buffer buf (erase-buffer))
      (start-process "leeter" buf shell-file-name
                     shell-command-switch
                     (concat leeter-bin " " cmd))
      (display-buffer buf)))

  (defvar leeter-mode-map
    (let ((map (make-sparse-keymap)))
      (define-key map (kbd "C-c l r") (lambda () (interactive) (leeter--run "run")))
      (define-key map (kbd "C-c l d") (lambda () (interactive) (leeter--run "debug")))
      (define-key map (kbd "C-c l b") (lambda () (interactive) (leeter--run "bench --iters 500")))
      (define-key map (kbd "C-c l t") (lambda () (interactive) (leeter--run "stress --iters 200")))
      (define-key map (kbd "C-c l p") (lambda () (interactive) (leeter--run "replay")))
      (define-key map (kbd "C-c l f") (lambda () (interactive) (leeter--run "fetch" t)))
      (define-key map (kbd "C-c l s") (lambda () (interactive) (leeter--run "session" t)))
      (define-key map (kbd "C-c l a") (lambda () (interactive) (leeter--run "stats" t)))
      map))

  (define-minor-mode leeter-mode
    "Minor mode for Leeter keybindings."
    :keymap leeter-mode-map)

  (leeter-mode 1)
  (message "[leeter] Emacs integration loaded. C-c l + r/d/b/t/p/f/s/a"))))))
