;;; leeter.el --- Leeter LeetCode framework integration for Emacs
;; AUTO-GENERATED by `leeter setup emacs`. Re-run to update.
;;
;; Usage: add to your init.el:
;;   (load "/path/to/leeter/adapters/emacs/leeter.el" t)
;;   ; or if you have the alias on exec-path:
;;   (require 'leeter)

(defgroup leeter nil
  "Leeter LeetCode framework integration."
  :group 'tools)

(defcustom leeter-bin
  (or (executable-find "leeter")
      (expand-file-name
       "cli/leeter.py"
       (file-name-directory (or load-file-name buffer-file-name default-directory))))
  "Path to the leeter binary or leeter.py script."
  :type 'string
  :group 'leeter)

(defcustom leeter-prefix "C-c l"
  "Key prefix for Leeter commands."
  :type 'string
  :group 'leeter)

(defun leeter--run (subcmd &optional use-repo-root)
  "Run `leeter SUBCMD' via compile-mode.
When USE-REPO-ROOT is non-nil, run from the git repo root instead of
the current buffer's directory."
  (let* ((problem-dir default-directory)
         (git-root (locate-dominating-file default-directory ".git"))
         (default-directory (if use-repo-root (or git-root default-directory)
                              problem-dir))
         (cmd (if (string-suffix-p ".py" leeter-bin)
                  (format "python3 %s %s" leeter-bin subcmd)
                (format "%s %s" leeter-bin subcmd))))
    (compile cmd)))

;;
;; Command definitions
;;

(defun leeter-run ()
  "Run the current LeetCode problem."
  (interactive)
  (leeter--run "run"))

(defun leeter-debug ()
  "Debug the current LeetCode problem."
  (interactive)
  (leeter--run "debug"))

(defun leeter-bench ()
  "Benchmark the current LeetCode problem."
  (interactive)
  (leeter--run "bench --iters 500"))

(defun leeter-stress ()
  "Stress test the current LeetCode problem."
  (interactive)
  (leeter--run "stress --iters 200"))

(defun leeter-replay ()
  "Replay the last run of the current LeetCode problem."
  (interactive)
  (leeter--run "replay"))

(defun leeter-paste ()
  "Paste clipboard content to input.txt."
  (interactive)
  (leeter--run "paste"))

(defun leeter-fetch (id)
  "Fetch LeetCode problem by ID."
  (interactive "sProblem ID: ")
  (leeter--run (format "fetch %s" id) t))

(defun leeter-session ()
  "Show the current Leeter session."
  (interactive)
  (leeter--run "session" t))

(defun leeter-stats ()
  "Show overall Leeter stats."
  (interactive)
  (leeter--run "stats" t))

(defun leeter-clean ()
  "Clean build artifacts for the current problem."
  (interactive)
  (leeter--run "clean"))

;;
;; Keymap
;;

(defvar leeter-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "r") #'leeter-run)
    (define-key map (kbd "d") #'leeter-debug)
    (define-key map (kbd "b") #'leeter-bench)
    (define-key map (kbd "t") #'leeter-stress)
    (define-key map (kbd "p") #'leeter-replay)
    (define-key map (kbd "v") #'leeter-paste)
    (define-key map (kbd "f") #'leeter-fetch)
    (define-key map (kbd "s") #'leeter-session)
    (define-key map (kbd "a") #'leeter-stats)
    (define-key map (kbd "c") #'leeter-clean)
    map)
  "Keymap for Leeter commands, bound under `leeter-prefix'.")

(defun leeter-setup-keys ()
  "Bind Leeter commands under `leeter-prefix'."
  (global-set-key (kbd leeter-prefix) leeter-mode-map))

;;
;; Minor mode (for project-local activation via .dir-locals.el)
;;

(define-minor-mode leeter-mode
  "Minor mode providing Leeter keybindings."
  :lighter " Leeter"
  :keymap leeter-mode-map)

;;
;; Activation
;;

(leeter-setup-keys)

(provide 'leeter)
;;; leeter.el ends here
